apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webapp-ingress
spec:
  rules:
  - host: dns_alb
    http:
      paths:
        backend:
          serviceName: frontend-svc
          servicePort: 80
      - path: /backend
        backend:
          serviceName: backend-svc
          servicePort: 80
